FROM php:7.0-fpm

RUN apt-get upgrade
RUN apt-get update

# PHP basic extensions
RUN docker-php-ext-install pdo_mysql \
    && docker-php-ext-install json \
    && apt-get install -y zlib1g-dev libicu-dev g++  \
    && docker-php-ext-install -j$(nproc) intl \
    && apt-get install -y libpng-dev \
    && apt-get install -y libfreetype6-dev libjpeg62-turbo-dev \
    && docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ \
    && docker-php-ext-install -j$(nproc) gd \
    && apt install -y libmcrypt-dev \
    && docker-php-ext-install mcrypt \
    && apt install -y libxslt-dev \
    && docker-php-ext-install xsl \
    && docker-php-ext-install zip \
    && apt-get install -y libxml2-dev php-soap \
    && apt-get clean -y \
    && docker-php-ext-install soap \
    && curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer \
    && apt install -y git \
    && pecl install xdebug \
    && docker-php-ext-enable xdebug

#    Might need to test if xdebug works well Xdebug On Demand for CLI PHP Scripts in PhpStorm
#&& sed -i '1 a xdebug.remote_autostart=true' /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini \
#&& sed -i '1 a xdebug.remote_mode=req' /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini \
#&& sed -i '1 a xdebug.remote_handler=dbgp' /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini \
#&& sed -i '1 a xdebug.remote_connect_back=1 ' /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini \
#&& sed -i '1 a xdebug.remote_port=9001' /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini \
#&& sed -i '1 a xdebug.remote_enable=1' /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini \

# Permissions
RUN usermod -u 1000 www-data
RUN usermod -G staff www-data
